"""Lightweight i18n for the wizard surface.

Translations live in ``chunkvault/wizard/locales/<bcp47>.json``. Adding a
new language is a no-code change: drop a new JSON next to the others
with a ``_meta`` block + the same keys, and it shows up in the
"Switch language" picker on next launch.

A locale's JSON file may omit any key; missing keys fall back to the
``en`` table (the source of truth). A locale's ``_meta.review_needed``
flag (boolean) marks translations that were generated by a non-native
hand and would benefit from native review — surfaced in the picker so
users know what they're choosing.

Locale resolution order on startup:

1. explicit call to :func:`set_locale`
2. ``CHUNKVAULT_LANG`` env var (any registered bcp47 tag, or "en"/"zh")
3. config file ``~/.chunkvault/config.json`` ``locale`` field
4. system locale (``LANG``/``LC_ALL`` matched against the registry's
   tags + a few common aliases — ``zh_CN`` -> ``zh-CN`` etc.)
5. ``en``

Scope is intentionally narrow: high-touch UI strings (menu labels,
guide panel, op intros, common confirms). Deep-down technical messages
(progress event labels, file paths, error class names) stay in English
because translating them risks diverging from code identifiers users
will see in stack traces or grep output.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

_LOCALES_DIR = Path(__file__).parent / "locales"
_CONFIG_DIR = Path.home() / ".chunkvault"
_CONFIG_PATH = _CONFIG_DIR / "config.json"

DEFAULT_LOCALE = "en"


@dataclass(frozen=True)
class LocaleInfo:
    """Metadata for one locale loaded from disk."""
    tag: str                 # bcp47 tag, e.g. "zh-CN"
    name: str                # English-readable name, e.g. "Simplified Chinese"
    native_name: str         # As written in that language, e.g. "简体中文"
    review_needed: bool = False


_strings: dict[str, dict[str, str]] = {}     # tag -> {key: text}
_locales: dict[str, LocaleInfo] = {}         # tag -> LocaleInfo
_current: str = DEFAULT_LOCALE


def _load_all_locales() -> None:
    """Scan ``locales/`` and load every ``*.json`` into the registry."""
    _strings.clear()
    _locales.clear()
    if not _LOCALES_DIR.is_dir():
        return
    for path in sorted(_LOCALES_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict):
            continue
        meta = data.pop("_meta", None) or {}
        tag = (meta.get("bcp47") or path.stem).strip()
        if not tag:
            continue
        _locales[tag] = LocaleInfo(
            tag=tag,
            name=meta.get("name") or tag,
            native_name=meta.get("native_name") or meta.get("name") or tag,
            review_needed=bool(meta.get("review_needed", False)),
        )
        # Keep only string values; meta and any nested structures are dropped.
        _strings[tag] = {
            k: v for k, v in data.items() if isinstance(v, str)
        }


def list_locales() -> list[LocaleInfo]:
    """Return all registered locales, English-name sorted."""
    return sorted(_locales.values(), key=lambda L: L.name.lower())


def get_locale_info(tag: str) -> LocaleInfo | None:
    return _locales.get(tag)


def get_locale() -> str:
    return _current


def _normalize_tag(raw: str | None) -> str | None:
    """Turn ``zh_CN`` / ``zh_cn.UTF-8`` / ``ZH-CN`` into a registered tag,
    or ``None`` if there's no match."""
    if not raw:
        return None
    raw = raw.replace("_", "-").split(".")[0].strip()
    if not raw:
        return None
    # Direct match first (case-sensitive — bcp47 is case-sensitive in spec
    # but real-world env vars vary, so also try a case-folded pass).
    if raw in _locales:
        return raw
    folded = raw.lower()
    for tag in _locales:
        if tag.lower() == folded:
            return tag
    # Two-letter language match: "zh_TW" provided, only "zh-CN" registered
    # → fall through to language-only match against "zh".
    primary = folded.split("-")[0]
    if primary in _locales:
        return primary
    # Last resort: any registered tag whose primary matches the requested
    # primary (e.g. "zh" requested, prefer "zh-CN" over "zh-TW" only because
    # of dict order — both are reasonable).
    for tag in _locales:
        if tag.lower().split("-")[0] == primary:
            return tag
    return None


def _load_config_locale() -> str | None:
    try:
        if _CONFIG_PATH.is_file():
            data = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
            return _normalize_tag(data.get("locale"))
    except (OSError, json.JSONDecodeError):
        pass
    return None


def _system_locale_hint() -> str | None:
    for var in ("LC_ALL", "LANG", "LANGUAGE"):
        norm = _normalize_tag(os.environ.get(var))
        if norm is not None:
            return norm
    return None


def _resolve_initial_locale() -> str:
    env = _normalize_tag(os.environ.get("CHUNKVAULT_LANG"))
    if env is not None:
        return env
    cfg = _load_config_locale()
    if cfg is not None:
        return cfg
    sys_hint = _system_locale_hint()
    if sys_hint is not None:
        return sys_hint
    return DEFAULT_LOCALE


def set_locale(locale: str, *, persist: bool = True) -> Path | None:
    """Change the active locale. Persists to ``~/.chunkvault/config.json``
    by default so the choice survives across runs.

    Raises ``ValueError`` if the locale isn't registered (no JSON file).
    """
    global _current
    if locale not in _locales:
        raise ValueError(
            f"unknown locale: {locale!r} "
            f"(known: {', '.join(sorted(_locales)) or '(none loaded)'})"
        )
    _current = locale
    if persist:
        try:
            _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
            data: dict = {}
            if _CONFIG_PATH.is_file():
                try:
                    data = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
                    if not isinstance(data, dict):
                        data = {}
                except json.JSONDecodeError:
                    data = {}
            data["locale"] = locale
            _CONFIG_PATH.write_text(
                json.dumps(data, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            return _CONFIG_PATH
        except OSError:
            return None
    return None


def t(key: str, /, **fmt: object) -> str:
    """Look up a string by key, formatted with ``**fmt``.

    Falls back to the English entry on a missing key for the current
    locale; falls back to the key itself if even English lacks it (so
    the bug is loud and visible).
    """
    primary = _strings.get(_current, {}).get(key)
    text = primary or _strings.get(DEFAULT_LOCALE, {}).get(key) or key
    return text.format(**fmt) if fmt else text


# Initialize on import.
_load_all_locales()
_current = _resolve_initial_locale()
